// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zealightlabs_assessment.Data;

#nullable disable

namespace zealightlabs_assessment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250202215428_FullMigration")]
    partial class FullMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("zealightlabs_assessment.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothings"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electronics"
                        });
                });

            modelBuilder.Entity("zealightlabs_assessment.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Delicious cheese pizza",
                            Name = "Pizza",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Juicy beef burger",
                            Name = "Burger",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Italian pasta with sauce",
                            Name = "Pasta",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Fresh vegetable salad",
                            Name = "Salad",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Crispy fried chicken",
                            Name = "Fried Chicken",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Cotton T-shirt",
                            Name = "T-shirt",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Comfortable denim jeans",
                            Name = "Jeans",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Winter jacket",
                            Name = "Jacket",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Warm wool sweater",
                            Name = "Sweater",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Elegant skirt for women",
                            Name = "Skirt",
                            Price = 22.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "High-performance laptop",
                            Name = "Laptop",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Latest smartphone with great features",
                            Name = "Smartphone",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Noise-cancelling headphones",
                            Name = "Headphones",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Wearable fitness tracker",
                            Name = "Smart Watch",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "LED Smart TV with 4K resolution",
                            Name = "TV",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "Pepperoni pizza",
                            Name = "Pizza",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Chicken sandwich with veggies",
                            Name = "Sandwich",
                            Price = 6.49m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Vanilla and chocolate ice cream",
                            Name = "Ice Cream",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Glazed donut",
                            Name = "Donut",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Grilled steak",
                            Name = "Steak",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Casual summer shorts",
                            Name = "Shorts",
                            Price = 18.99m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "Women's blouse",
                            Name = "Blouse",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "Leather shoes",
                            Name = "Shoes",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Formal dress",
                            Name = "Dress",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Description = "Baseball cap",
                            Name = "Cap",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Android tablet",
                            Name = "Tablet",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "Gaming console with two controllers",
                            Name = "Game Console",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "Bluetooth portable speaker",
                            Name = "Speaker",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "Digital camera with zoom",
                            Name = "Camera",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Description = "LED smart bulb with remote control",
                            Name = "Smart Bulb",
                            Price = 19.99m
                        });
                });

            modelBuilder.Entity("zealightlabs_assessment.Entities.Product", b =>
                {
                    b.HasOne("zealightlabs_assessment.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("zealightlabs_assessment.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
